name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Build Astro
        run: bun run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: karmakarmeghdip-portfolio
          entrypoint: dist/server/entry.mjs